services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/${DB_NAME:?err}
      SONAR_JDBC_USERNAME: ${DB_USER:?err}
      SONAR_JDBC_PASSWORD: ${DB_PASS:?err}
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASS:?err}
      POSTGRES_DB: ${DB_NAME:?err}
    volumes:
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres:
  postgres_data: